base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        '', TemplateView.as_view(template_name="homepage.html"), name="homepage"
    ),
    path('users/', include('users.urls')),
    path('questions/', include('questions.urls')),
    path('tags/', include('tags.urls')),
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

questions/urls.py
from django.urls import path
from . import views

app_name = 'questions'

urlpatterns = [
    path('', views.QuestionListView.as_view(), name='question_list'),
    path('<int:pk>/', views.QuestionDetailView.as_view(), name='question_detail'),
    path('create/', views.QuestionCreateView.as_view(), name='question_create'),
    path('<int:pk>/update/', views.QuestionUpdateView.as_view(), name='question_update'),
    path('<int:pk>/question_rank/', views.QuestionRank.as_view(), name='question_rank'),
    path('<int:pk>/answer_create/', views.AnswerCreateView.as_view(), name='answer_create'),
    path('<int:pk>/<int:answer_pk>/', views.AnswerRank.as_view(), name='answer_rank'),
]

tags/urls.py
from django.urls import path
from . import views

app_name = 'tags'


urlpatterns = [
    path('', views.TagListView.as_view(), name='tag_list'),
    path('<int:pk>/', views.TagDetailView.as_view(), name='tag_detail'),
]

users/urls.py
from django.urls import path
from . import views

app_name="users"

urlpatterns = [
    path('', views.UserListView.as_view(), name='user_list'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('update/', views.UserUpdateView.as_view(), name='user_update'),
    path('detail/<int:pk>/', views.UserDetailView.as_view(), name='user_detail'),
    
]

questions/models.py
from django.db import models

from users.models import User
from django.shortcuts import reverse
from tags.models import Tag


class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=300)
    content = models.TextField()
    tag = models.ManyToManyField(Tag)
    image = models.ImageField(
        upload_to="questions_image", blank=True, null=True
    )
    rank = models.IntegerField(null=True, blank=True, default=0)
    created_date = models.DateField(auto_now_add=True)

    objects = models.Manager()

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("questions:question_detail", kwargs={"pk": self.pk})

    def increase_rank(self):    # f object race condition
        self.rank += 1
        self.save()

    def decrease_rank(self):    # f object race condition
        self.rank -= 1
        self.save()


class QuestionAnswer(models.Model):
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, related_name='answers'
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    parent = models.ForeignKey(
        'self', null=True, blank=True, on_delete=models.CASCADE,
        related_name='replies'
    )
    content = models.TextField(max_length=300)
    image = models.ImageField(upload_to="answers_image", blank=True, null=True)
    rank = models.IntegerField(blank=True, null=True, default=0)
    created_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.content

    def increase_rank(self):    # f object race condition
        self.rank += 1
        self.save()

    def decrease_rank(self):     # f object race condition
        self.rank -= 1
        self.save()


# BaseVote abstract
class QuestionVote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    voted_parent = models.ForeignKey(
        Question, null=True, blank=True, on_delete=models.SET_NULL
    )
    vote_value = models.CharField(
        max_length=10, null=True, blank=True, default='draft'
    )


class AnswerVote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    voted_parent = models.ForeignKey(
        QuestionAnswer, null=True, blank=True, on_delete=models.SET_NULL
    )
    vote_value = models.CharField(
        max_length=10, null=True, blank=True, default='draft'
    )

questions/forms.py
from django import forms

from .models import Question, QuestionAnswer
from tags.models import Tag
from crispy_forms.helper import FormHelper

class QuestionCreateForm(forms.ModelForm):

    class Meta:
        model = Question
        fields = [
            'title', 'content', 'image', 'tag'
        ]


class QuestionAnswerForm(forms.ModelForm):

    class Meta:
        model = QuestionAnswer
        fields = ['content']

        widgets = {
            'content': forms.Textarea(attrs={'rows': 2})
        }

# class QuestionFilterForm(forms.Form):
#     title = forms.CharField()
#     tag = forms.CharField()
#     user = forms.CharField()
#     min_date = forms.CharField()
#     max_date = forms.CharField()
#     min_rank = forms.CharField()
#     max_rank = forms.CharField()

questions/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.http import HttpResponseRedirect
from django.views.generic import CreateView, UpdateView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
# from django.db.models import Q
from django.views import View


from .models import Question, QuestionAnswer, QuestionVote, AnswerVote
from .forms import QuestionCreateForm, QuestionAnswerForm
from .utils import filter_question, RankMixin


class QuestionCreateView(LoginRequiredMixin, CreateView):
    model = Question
    form_class = QuestionCreateForm

    def form_valid(self, form):
        question = form.save(commit=False)
        question.user = self.request.user
        question.save()
        return super().form_valid(form)


class QuestionListView(View):
    template_name = "questions/question_list.html"

    def get_queryset(self):
        return Question.objects.all()

    def get(self, request, *args, **kwargs):
        context = {"object_list": self.get_queryset()}

        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        params = request.POST
        print(params)
        kwargs = {
            '{0}__{1}'.format('title', 'icontains'): params.get('title'),
            '{0}__{1}__{2}'.format('tag', 'title', 'icontains'): params.get('tag'),
            '{0}__{1}__{2}'.format('user', 'username', 'icontains'): params.get('user'),
            '{0}__{1}'.format('created_date', 'gte'): params.get('min_date'),
            '{0}__{1}'.format('created_date', 'lte'): params.get('max_date'),
            '{0}__{1}'.format('rank', 'gte'): params.get('min_rank'),
            '{0}__{1}'.format('rank', 'lte'): params.get('max_rank'),
        }
        questions_raw = Question.objects.all()
        questions = filter_question(questions_raw, **kwargs)
        context = {"object_list": questions}

        return render(request, self.template_name, context)


class QuestionDetailView(DetailView):
    model = Question

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["answers"] = self.object.answers.all().filter(parent=None)
        context["form"] = QuestionAnswerForm()
        try:
            question_vote = QuestionVote.objects.get(
                user=self.request.user, voted_parent=self.object
            )
            context["question_vote"] = question_vote
        except BaseException:
            context["question_vote"] = 'Oy kullanmadınız'
        return context


class QuestionUpdateView(LoginRequiredMixin, UpdateView):
    model = Question
    form_class = QuestionCreateForm


class QuestionRank(RankMixin, View):
    vote_model = QuestionVote


class AnswerCreateView(LoginRequiredMixin, View):

    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')

        obj = get_object_or_404(Question, pk=pk)
        return obj

    def post(self, request, *args, **kwargs):
        question = self.get_object()

        form = QuestionAnswerForm(data=request.POST)
        if form.is_valid():
            try:
                parent_id = int(request.POST.get('parent_id'))
            except BaseException:
                parent_id = None

            if parent_id:
                parent_answer = QuestionAnswer.objects.get(id=parent_id)
                if parent_answer:
                    child_answer = form.save(commit=False)
                    child_answer.parent = parent_answer

            question_answer = form.save(commit=False)
            question_answer.question = question
            question_answer.user = self.request.user
            question_answer.save()
            return HttpResponseRedirect(self.get_object().get_absolute_url())
        return reverse("questions:question_detail", kwargs={"pk": question.pk})


class AnswerRank(RankMixin, View):
    vote_model = AnswerVote

questions/templates/questions/question_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block body %}


<!-- Page Content -->
<div class="container">

  <div class="row">

    <!-- Post Content Column -->
    <div class="col-lg-8">

      <!-- Title -->
      <h1 class="mt-4"> {{ object.title }} </h1>

      <!-- Author -->
      <small> <p class="lead">
        by
        <a href="{% url 'users:user_detail' pk=object.user.pk %}">{{ object.user }}</a> on {{ object.created_date }}
      </p></small>



      {% if object.image %}

      <img class="img-fluid rounded" src=" {{ object.image.url }} " alt="">

      {% endif %}

      <hr>

      <p>{{ object.content }}</p>

      <hr>
      <p>Score of this question: <b>{{ object.question_rank }}</b> Your last choice: {{question_vote.vote_value}}</p>
      <form action="{% url 'questions:question_rank' pk=object.pk %}" method="POST">{% csrf_token %}

        <div class="form-check-inline">
          <label class="form-check-label">
            <input type="radio" class="form-check-input" value="decrease" name="vote">Decrease
          </label>
        </div>
        <div class="form-check-inline">
          <label class="form-check-label">
            <input type="radio" class="form-check-input" value="increase" name="vote">Increase
          </label>
        </div>
        <button type="submit" class="btn btn-sm btn-warning">Vote</button>
      </form>
      <!-- Comments Form -->
      <div class="card my-4">
        <h5 class="card-header">Leave a Answer:</h5>
        <div class="card-body">
          <form method="POST" action="{% url 'questions:answer_create' pk=object.pk %}"> {% csrf_token %}
            {{ form|crispy }}
            {% comment %} <div class="form-group">
              <textarea class="form-control" name="answer" rows="3"></textarea>
            </div> {% endcomment %}
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        </div>
      </div>

      {% for answer in answers %}
      <!-- Comment with nested comments -->
      <div class="media mb-4">
        <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/40x40" alt="">
        <div class="media-body">
          <h5 class="mt-0"> {{ answer.user }} <small> on {{answer.created_date}}</small></h5>
          {{ answer.content }}
          <form action="{% url 'questions:answer_rank' pk=object.pk answer_pk=answer.pk %}" method="POST">{% csrf_token %}
            Score of this answer: <b>{{answer.answer_rank}}</b>
            <div class="form-check-inline">
              <label class="form-check-label">
                <input type="radio" class="form-check-input" value="decrease" name="vote">Decrease
              </label>
            </div>
            <div class="form-check-inline">
              <label class="form-check-label">
                <input type="radio" class="form-check-input" value="increase" name="vote">Increase
              </label>
            </div>
            <button type="submit" class="btn btn-sm btn-warning">Vote</button>
          </form>

          {% for reply in answer.replies.all %}

          <div class="media mt-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/40x40" alt="">
            <div class="media-body">
              <h5 class="mt-0">{{ reply.user }} <small> on {{answer.created_date}}</small></h5>
              {{ reply.content }}
            </div>
          </div>

          {% endfor %}
          <form method="POST" action="{% url 'questions:answer_create' pk=object.pk %}"> {% csrf_token %}
            {{form|crispy}}
            <input type="hidden" name="parent_id" value="{{ answer.id }}">
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
      </div>
    </div>



      {% endfor %}
    </div>


    {% endblock body %}

questions/templates/questions/question_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block body %}
<br>
<div class="row" >
    <div class="col-4 offset-4">

        <form method='POST'  enctype="multipart/form-data">{% csrf_token %}
            {{form.media}}
            
            {{form|crispy}}
            <button type="submit" class="btn btn-primary"> Create</button>
            <br><br>
        </form>
      </div>
  </div>
{% endblock body %}

questions/templates/questions/question_list.html
{% extends "base.html" %}

{% block body %}

<div class="container">
  <h1 class="my-4">Questions
  </h1>

  {% if request.user.is_authenticated %}
  <a href="{% url 'questions:question_create' %}" class="btn btn-primary" style="background-color: #314d47;">Create
    Question</a>
  <hr>

  {% endif %}


  <form method="POST" action="."> {% csrf_token %}
    <div class="form-row">
      <div class="form-group col-md-3">
        <label>Search in Titles</label>
        <input type="text" name="title" class="form-control" placeholder="Write Title">
      </div>
      <div class="form-group col-md-3">
        <label>Search in Tags</label>
        <input type="text" name="tag" class="form-control" placeholder="Write Tag">
      </div>
      <div class="form-group col-md-3">
        <label>Search in Users</label>
        <input type="text" name="user" class="form-control" placeholder="Write Username">
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-3">
        <label>Search by Min Date</label>
        <input type="date" name="min_date" class="form-control" placeholder="Min Date">
      </div>
      <div class="form-group col-md-3">
        <label>Search by Max Date</label>
        <input type="date" name="max_date" class="form-control" placeholder="Max Date">
      </div>
      <div class="form-group col-md-3">
        <label>Search by Min Rank</label>
        <input type="number" name="min_rank" class="form-control" placeholder="Min Rank">
      </div>
      <div class="form-group col-md-3">
        <label>Search by Max Rank</label>
        <input type="number" name="max_rank" class="form-control" placeholder="Max Rank">
      </div>

    </div>


    <button type="submit" class="btn btn-danger" style="background-color: #314d47;"> Search</button>
  </form>

  <div class="list-group">



    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Title</th>
          <th scope="col">Tag</th>
          <th scope="col">User of the Question</th>
          <th scope="col">Created Date</th>
          <th scope="col">Rank</th>
          <th scope="col">Answer</th>
        </tr>
      </thead>
      <tbody>
        {% for question in object_list %}
        <tr>
          <th scope="row"> {{forloop.counter}} </th>
          <td> <a href=" {% url 'questions:question_detail' pk=question.pk %} "> {{ question.title|truncatechars:20}}
            </a></td>
          <td> {% for tag in question.tag.all %}
            <a href=" {% url 'tags:tag_detail' pk=tag.pk %} ">{{tag.title}}, </a>
            {% endfor %} </td>
          <td> {{ question.user}} </td>
          <td> {{ question.created_date}} </td>
          <td> {{ question.rank}} </td>
          <td> {{ question.answers.count }} </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>


  </div>
</div>

{% endblock body %}