base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        '', TemplateView.as_view(template_name="homepage.html"), name="homepage"
    ),
    path('users/', include('users.urls')),
    path('questions/', include('questions.urls')),
    path('tags/', include('tags.urls')),
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

questions/urls.py
from django.urls import path
from . import views

app_name = 'questions'

urlpatterns = [
    path('', views.QuestionListView.as_view(), name='question_list'),
    path('<int:pk>/', views.QuestionDetailView.as_view(), name='question_detail'),
    path('create/', views.QuestionCreateView.as_view(), name='question_create'),
    path('<int:pk>/update/', views.QuestionUpdateView.as_view(), name='question_update'),
    path('<int:pk>/question_rank/', views.QuestionRank.as_view(), name='question_rank'),
    path('<int:pk>/answer_create/', views.AnswerCreateView.as_view(), name='answer_create'),
    path('<int:pk>/<int:answer_pk>/', views.AnswerRank.as_view(), name='answer_rank'),
]

tags/urls.py
from django.urls import path
from . import views

app_name = 'tags'


urlpatterns = [
    path('', views.TagListView.as_view(), name='tag_list'),
    path('<int:pk>/', views.TagDetailView.as_view(), name='tag_detail'),
]

users/urls.py
from django.urls import path
from . import views

app_name="users"

urlpatterns = [
    path('', views.UserListView.as_view(), name='user_list'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('update/', views.UserUpdateView.as_view(), name='user_update'),
    path('detail/<int:pk>/', views.UserDetailView.as_view(), name='user_detail'),
    
]

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg" style="background-color:#314d47;">
    <a class="navbar-brand"  style="color: white;" href="{% url 'homepage' %}">KS</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="navbar-brand" style="color: white;" href="{% url 'questions:question_list' %}" >Questions <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="navbar-brand" style="color: white;" href="{% url 'users:user_list' %}">Users</a>
        </li>
        <li class="nav-item">
          <a class="navbar-brand"  style="color: white;" href="{% url 'tags:tag_list' %}">Tags</a>
        </li>
        <li class="nav-item">
          <a class="navbar-brand" style="color: white;" href="#">Jobs</a>
        </li>
        
      </ul>
      
     

      <ul class="navbar-nav ml-auto">
            

        {% if request.user.is_authenticated %}
        <li class="nav-item active">
          <a class="btn btn-outline-danger" style="color: white;" href="{% url 'logout' %}">Logout</a>
        </li>

        {% else %}
          <li class="nav-item active">
          <a class="btn btn-outline-danger" style="color: white;" href="{% url 'users:register' %}">Register</a>
        </li> &nbsp;&nbsp;
        <li class="nav-item active">
          <a class="btn btn-outline-danger" style="color: white;" href="{% url 'login' %}">Login</a>
        </li>

        {% endif %}
                 
      </ul>

      <!-- <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>  -->


    </div>
  </nav>