base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        '', TemplateView.as_view(template_name="homepage.html"), name="homepage"
    ),
    path('users/', include('users.urls')),
    path('questions/', include('questions.urls')),
    path('tags/', include('tags.urls')),
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

questions/urls.py
from django.urls import path
from . import views

app_name = 'questions'

urlpatterns = [
    path('', views.QuestionListView.as_view(), name='question_list'),
    path('<int:pk>/', views.QuestionDetailView.as_view(), name='question_detail'),
    path('create/', views.QuestionCreateView.as_view(), name='question_create'),
    path('<int:pk>/update/', views.QuestionUpdateView.as_view(), name='question_update'),
    path('<int:pk>/question_rank/', views.QuestionRank.as_view(), name='question_rank'),
    path('<int:pk>/answer_create/', views.AnswerCreateView.as_view(), name='answer_create'),
    path('<int:pk>/<int:answer_pk>/', views.AnswerRank.as_view(), name='answer_rank'),
]

tags/urls.py
from django.urls import path
from . import views

app_name = 'tags'


urlpatterns = [
    path('', views.TagListView.as_view(), name='tag_list'),
    path('<int:pk>/', views.TagDetailView.as_view(), name='tag_detail'),
]

tags/models.py
from django.db import models

# Create your models here.

class Tag(models.Model):
    title       = models.CharField(max_length=50)
    content     = models.TextField(null=True, blank=True)
    tag_image   = models.ImageField(upload_to="tag_image")

    def __str__(self):
        return self.title
    

tags/views.py
from .models import Tag


from django.shortcuts import render
from django.views.generic import CreateView, UpdateView, DetailView, ListView


class TagListView(ListView):
    model = Tag


class TagDetailView(DetailView):
    model = Tag

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["questions"] = self.object.question_set.all()
        return context
    

tags/templates/tags/tag_detail.html
{% extends "base.html" %}

{% block body %}


  <!-- Page Content -->
  <div class="container">

        <!-- Heading Row -->
        <div class="row align-items-center my-5">
          <div class="col-lg-5">
            {% if object.tag_image %}
                <img class="img-fluid rounded mb-4 mb-lg-0" src="{{object.tag_image.url}}" style =" heigh:300px; width:300px;">
            {% endif %}


            
          </div>
          <!-- /.col-lg-8 -->
          <div class="col-lg-5">
            <h1 class="font-weight-light">{{object.title}}</h1>
            <p>{{object.content}}</p>
          
          </div>
          <!-- /.col-md-4 -->
        </div>
        <!-- /.row -->
    
        <!-- Call to Action Well -->
        <div class="card text-white bg-secondary my-5 py-4 text-center">
          <div class="card-body">
            <p class="text-white m-0">Question about {{object.title}}</p>
          </div>
        </div>


<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Tag</th>
      <th scope="col">User of the Question</th>
      <th scope="col">Created Date</th>
      <th scope="col">Rank</th>
      <th scope="col">Answer</th>
    </tr>
  </thead>
  <tbody>
  {% for question in questions %}
    <tr>
      <th scope="row"> {{forloop.counter}} </th>
      <td> <a href=" {% url 'questions:question_detail' pk=question.pk %} "> {{ question.title|truncatechars:20}} </a></td>
      <td> {% for tag in question.tag.all %} 
      <a href=" {% url 'tags:tag_detail' pk=tag.pk %} ">{{tag.title}}, </a> 
       {% endfor %} </td> 
      <td> {{ question.user}} </td>
      <td> {{ question.created_date}} </td>
      <td> {{ question.question_rank}} </td>
      <td> {{ question.answers.count }} </td>
    </tr>
    {% endfor %}
  </tbody>
</table>




{% endblock body %}

tags/templates/tags/tag_list.html
{% extends "base.html" %}

{% block body %}

<div class="container">

    <!-- Page Heading -->
    <h1 class="my-4">Tags
      <small>Programming Language</small>
    </h1>
  

    <div class="row">
      {% for tag in object_list  %}
      <div class="col-lg-4 col-sm-6 mb-4">
      
        <div class="card h-100">
        
          <a href=" {% url 'tags:tag_detail' pk=tag.pk %}">
            {% if tag.tag_image %}
            <img class="card-img-top" src="{{tag.tag_image.url}}">
            {% endif %}  
            
            </a>
          <div class="card-body">
            <h4 class="card-title">
              <a href="{% url 'tags:tag_detail' pk=tag.pk %}"> {{ tag.title }}</a>
            </h4>
            <p class="card-text">{{tag.content|truncatewords:30}}</p>     
          </div>     
        </div>
      </div>
      {% endfor %}
</div>



{% endblock body %}