base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        '', TemplateView.as_view(template_name="homepage.html"), name="homepage"
    ),
    path('users/', include('users.urls')),
    path('questions/', include('questions.urls')),
    path('tags/', include('tags.urls')),
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

users/urls.py
from django.urls import path
from . import views

app_name="users"

urlpatterns = [
    path('', views.UserListView.as_view(), name='user_list'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('update/', views.UserUpdateView.as_view(), name='user_update'),
    path('detail/<int:pk>/', views.UserDetailView.as_view(), name='user_detail'),
    
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField
from django.shortcuts import reverse

from tags.models import Tag



class User(AbstractUser):
    location        = models.CharField(max_length=100, null=True, blank=True)
    biography       = models.TextField(blank=True, null=True)
    image           = models.ImageField(null=True,blank=True, upload_to='users_image')
    github_link     = models.CharField(null=True, blank=True, max_length=100)
    tag             = models.ManyToManyField(Tag, blank=True, null=True)
    created_date    = models.DateField(auto_now_add=True)
    profession      = models.CharField(max_length=100, null=True, blank=True)
    phone           = PhoneNumberField(null=True, blank=True)
    experience      = models.CharField(null=True, blank=True, max_length=100)
    hourly_rate     = models.CharField(default='10$/hr',blank=True, null=True, max_length=30)
    total_project   = models.SmallIntegerField(null=True, blank=True)
    

    def get_absolute_url(self):
        return reverse("users:user_detail", kwargs={"pk": self.pk})
    

users/forms.py
from django import forms
from .models import User    

from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = UserCreationForm.Meta.fields + \
            ('username', 'first_name', 'last_name', 'image', 'email', 'phone',
             'location', 'profession', 'experience', 'hourly_rate',
             'total_project', 'biography', 'github_link', 'tag', )



class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'image', 'email', 'phone',
             'location', 'profession', 'experience', 'hourly_rate',
             'total_project', 'biography', 'github_link', 'tag',)

users/views.py
from django.shortcuts import render, reverse
from django.contrib.auth import login, authenticate
from django.urls import reverse_lazy, reverse
from django.shortcuts import redirect
from .models import User
from .forms import RegisterForm, UserUpdateForm
from django.views.generic import CreateView, UpdateView, DetailView, ListView


class RegisterView(CreateView):
    model = User
    form_class = RegisterForm
    
    def form_valid(self, form):
        resp = super().form_valid(form)
        user = authenticate(username=form.cleaned_data['username'] , password=form.cleaned_data['password1'])
        login(self.request, user)
        return resp


class UserDetailView(DetailView):
    model = User


class UserListView(ListView):
    model = User


class UserUpdateView(UpdateView):
    model = User
    form_class = UserUpdateForm
    

    def get_object(self, queryset=None):
        return self.request.user
    
    # def get_success_url(self):
    #     return reverse_lazy('users:user_detail',  kwargs={"pk" : self.object.id})
    #     #return reverse_lazy("users:user_list")

users/templates/users/user_detail.html
{% extends "base.html" %}

{% block body %}


<div class="container emp-profile" style="margin-top:20px;">
    <form method="post">
        <div class="row">
            <div class="col-md-4">
                
                <div class="profile-img">
                    {% if object.image %}
                    <img class="card-img-bottom" style="width:300px; height:200;" src="{{ object.image.url }}">
                    {% endif %}

                </div>
            </div>
            <div class="col-md-6">
              
                <div class="profile-head">
                    <h5>
                       Username: <strong>{{ object.username }}</strong> 
                        
                    </h5>
                    <h6>
                         {{object.first_name}} {{object.last_name}} 
                    </h6>
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab"
                                aria-controls="home" aria-selected="true">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab"
                                aria-controls="profile" aria-selected="false">Timeline</a>
                        </li>
                    </ul>
                </div>
            </div>
            
            {% if request.user.username == object.username %}
            <div class="col-md-2">
            
                <a href=" {% url 'users:user_update' %} " class="btn btn-danger"> Update </a>
            </div>
            
            {% endif %}
            
            
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="profile-work">
                    <p>Tags of Interest</p>
                    {% for tag in object.tag.all %}
                    <a href="">{{tag}}</a><br />
                    {% endfor %}
                    <p>SKILLS</p>
                  
                </div>
            </div>
            <div class="col-md-8">
                <div class="tab-content profile-tab" id="myTabContent">
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
    
                        <div class="row">
                            <div class="col-md-6">
                                <label>Name</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{object.first_name|title}} {{object.last_name|title}}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Email</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{object.email}}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Phone</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{object.phone}}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>location</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{object.location}}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <label>Your Bio</label><br />
                                <p>{{object.biography}}</p>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                        <div class="row">
                            <div class="col-md-6">
                                <label>Experience</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{object.experience}}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Hourly Rate</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{object.hourly_rate}}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Total Projects</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{object.total_project}}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Github link or name</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{object.github_link}}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock body %}

users/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block body %}

<br>
<div class="row">
    <div class="col-4 offset-4">

        <form method='POST' enctype="multipart/form-data">{% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <button type="submit" class="btn btn-primary"> Register</button>
            <br><br>
        </form>
    </div>


{% endblock body %}

users/templates/users/user_list.html
{% extends "base.html" %}

{% block body %}

<hr>
<div class="container bootstrap snippet">
    <div class="row">
        <div class="col-lg-12">
            <div class="main-box no-header clearfix">
                <div class="main-box-body clearfix">
                    <div class="table-responsive">
                        <table class="table user-list">
                            <thead>
                                <tr>
                                <th><span>User</span></th>
                                <th><span>Created</span></th>
                                </tr>
                            </thead>
                            <tbody>


                            {% for object in object_list %}
                            
                            
                                <tr>
                                    <td>
                                    {% if object.image %}
                                      <img class ="thumbnail" src="{{object.image.url}}" style="width:150px;height:150px">

                                    <br>
                                    {% endif %}
                                        <span class="user-subhead"><a href="{% url 'users:user_detail' pk=object.id %}">{{object.username}}</a> </span>
                                    </td>
                                    <td> {{ object.created_date}} </td>
                                </tr>
                                {% endfor %}  
                                
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock body %}